sudo: false
language: python
install:
  - easy_install distribute
  - pip install -r requirements.txt
script:
  - git clean -f -d -x
  - mkdocs build
after_success:
  - git config user.name "Deployment Bot"
  - git config user.email "deploy@travis-ci.org"
  - git remote add gh-token "https://${GH_TOKEN}@github.com/Makeroid/Documentation.git";
  - git fetch gh-token && git fetch gh-token gh-pages:gh-pages;
  - pip install mkdocs -U;
  - mkdocs gh-deploy -v --clean --remote-name gh-token;
