# Site Config
site_name: 'Makeroid Docs'
site_description: 'Makeroid Documentation'
site_author: 'Makeroid'
site_url: 'https://docs.makeroid.io'
  
# Repository
repo_name: Makeroid Docs
repo_url: https://github.com/Makeroid/Documentation
edit_uri: "blob/master/docs/"

#Copyright text in the footer
copyright: Copyright &copy; 2018 Makeroid

# Customization
extra:
  social:
    - type: globe
      link: https://www.makeroid.io
    - type: twitter
      link: https://twitter.com/Makeroid
    - type: facebook
      link: https://facebook.com/Makeroid
    - type: github
      link: https://github.com/Makeroid

# Material theme for MkDocs : https://github.com/squidfunk/mkdocs-material/
theme:
  name: 'material'
  feature:
    tabs: true
  palette:
    primary: white
    accent: pink
  logo: 'assets/logo.png'
  favicon: 'assets/favicon.ico'
  font:
    text: Roboto
    code: Roboto Mono

extra_css:
  - css/extra.css

extra_javascript:
  - 'https://code.jquery.com/jquery-3.3.1.min.js'
  - js/extra.js

plugins:
  - search
  - replace
  
#Markdown extensions: https://python-markdown.github.io/extensions/
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.toc:
      permalink: 'true'
  - markdown_include.include:
      base_path: docs
  - markdown.extensions.attr_list
  # PyMdown Extensions
  #- pymdownx.caret
  #- pymdownx.critic
  #- pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  #- pymdownx.inlinehilite
  #- pymdownx.keys
  #- pymdownx.mark
  #- pymdownx.smartsymbols
  #- pymdownx.superfences
  #- pymdownx.tasklist:
  #   custom_checkbox: true
  #- pymdownx.tilde


# Site navigation in the side bar
nav:
  - Getting Started:
    - Overview: index.md
    - Live Development:
      - Overview: live-development/index.md
      - Via WiFi: live-development/wifi.md
      - Via USB: live-development/usb.md
    - Other:
      - Extensions:
        - Overview: other/extensions/index.md
        - Create Extensions: other/extensions/create-extensions.md
      - Resources:
        - Overview: other/resources/index.md
        - Concept Cards: other/resources/concept-cards.md
      - Release Notes: other/release-notes/index.md
      - Backpack: other/backpack.md
  - Components:
    - Overview: components/index.md
    - Screen: components/screen.md
    - User Interface:
      - Button: components/user-interface/button.md
      - Checkbox: components/user-interface/checkbox.md
      - Linear Progressbar: components/user-interface/linear-progressbar.md
      - Circular Progress: components/user-interface/circular-progress.md
  - Blocks:
    - Control: blocks/control.md
    - Logic: blocks/logic.md
    - Math: blocks/math.md
    - Text: blocks/text.md
    - Lists: blocks/lists.md
    - Colors: blocks/colors.md
    - Variables: blocks/variables.md
    - Procedures: blocks/procedures.md
    - Any Component: blocks/any-componet.md



# Google Analyitcs
google_analytics:
  - 'UA-102230060-7'
  - 'auto'
